### PR TITLE
Add option to render a circle with a radius on DetailField

### PR DESCRIPTION
**Pull request by checkerschaf**
This adds the option to call `->circleRadius(1000)` with a circle radius in meters as an attribute. This is very helpful for my project so I think others may want to use it as well :)

PS: I've fixed the indentation of the DetailField.vue file as my last step. Not sure if you like it but I think it's better.

### CODE REVIEW

**Comment by mikebronner** [comment]
@checkerschaf Thanks! I'll take a look at this over the next week or so.

**Comment by checkerschaf** [comment]
@mikebronner Any updates on this one? :)

**Comment by mikebronner** [comment]
Thanks for the reminder! I got busy with Laravel 6 stuff these last two weeks. I'll try to look at it today.

**Comment by mikebronner** [comment]
@checkerschaf This is now added, with additional functionality (see readme) in release 0.1.11. Let me know how it works for you! Thanks for adding this. :)

**Pull request merged**
