### PR TITLE
Listen to Nova Events & Custom Label for geosearch box

### PR DESCRIPTION
**Pull request by angelformica**
Hello,

First, I want to say thank you for this Map field. It's very good!

I think this might be useful to merge:

This adds a listener to custom event to update the map position not only with the geosearch field, but also with any field in nova.

Any nova component just has to emit an event like this:

Nova.$emit("newcenter",{lat,lng})

and the map will pan to the new position.

If you need to use a custom name for the event you can define it in your field like this:

MapMarker::make(__('Location'))->listenToEventName('myCustomEventName')

After that, any component can update the map location like this:

Nova.$emit("newcenter",{lat,long})

And the map will pan to the new position.

This is useful if you have, like me, a table with a list of locations.

If you don't specify a custom event name, "newcenter" will be used by default.

This also, allows you to specify a custom search label for the geosearch box, allowing for localization, like this:

MapMarker::make(__('Location'))->searchLabel(__('Enter Address'))

I hope you find this helpful,

Best regards

### CODE REVIEW

**Comment by mikebronner** [comment]
Thank you @angelformica ! This sounds like a great feature update. Let me take a look and merge it if everything is ok. :)

**Comment by angelformica** [comment]
Awesome!

**Comment by mikebronner** [comment]
Hi @angelformica I see you have been making more updates. Let me know when you're finished, and I'll test it out.

**Comment by angelformica** [comment]
Hello @mikebronner 

Yes, It's ready for review. I hope everything is ok, and It can be merged. My last update was only to allow custom icons not only on the FormField but also on the DetailField.

Best regards,

**Comment by mikebronner** [comment]
@angelformica I have one issue with the proposed changes: how can I trigger the event from the resource class? To make this truly effective, we shouldn't have to create custom components just to trigger the event -- it would be great to trigger the event from any Nova field. What are your thoughts on this?

**Comment by angelformica** [comment]
> @angelformica I have one issue with the proposed changes: how can I trigger the event from the resource class? To make this truly effective, we shouldn't have to create custom components just to trigger the event -- it would be great to trigger the event from any Nova field. What are your thoughts on this?

Hello @mikebronner , I am sorry for the radio silence. I'm not really sure how this can be achieved. At a first thought I guess we would have to pass the name of the nova field we want to observe, to the nova map field, and then watch for changes. I would try to study the chances to do this.

**Pull request merged**
